-- [programmersSQL] 상품을 구매한 회원 비율 구하기
WITH REGISTERED_2021 AS(
    SELECT
        UI.USER_ID
    FROM 
        USER_INFO UI    
    WHERE
        YEAR(UI.JOINED) = 2021
),

PURCHASE_STATS AS (
    SELECT
        YEAR(OS.SALES_DATE) AS YEAR,
        MONTH(OS.SALES_DATE) AS MONTH,
        COUNT(DISTINCT OS.USER_ID) AS PURCHASED_USERS
    FROM
        ONLINE_SALE OS 
        JOIN REGISTERED_2021 R2 ON OS.USER_ID = R2.USER_ID
    GROUP BY
        YEAR(OS.SALES_DATE), MONTH(OS.SALES_DATE)
)


SELECT
    PS.YEAR,
    PS.MONTH,
    PS.PURCHASED_USERS,
    ROUND(PS.PURCHASED_USERS / (SELECT COUNT(*) FROM REGISTERED_2021), 1) AS PURCHASED_RATIO
FROM
    PURCHASE_STATS PS
ORDER BY 
    PS.YEAR, PS.MONTH
;