-- [programmersSQL]그룹별 조건에 맞는 식당 목록 출력하기
WITH MOST_ACTIVE_MEMBER AS (
    SELECT
        MEMBER_ID,
        COUNT(*) AS REVIEW_COUNT
    FROM
        REST_REVIEW
    GROUP BY
        MEMBER_ID
    ORDER BY
        REVIEW_COUNT DESC
    LIMIT 1
)

SELECT
    MP.MEMBER_NAME,
    RR.REVIEW_TEXT,
    DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM
    MEMBER_PROFILE MP
    JOIN REST_REVIEW RR ON MP.MEMBER_ID = RR.MEMBER_ID
    JOIN MOST_ACTIVE_MEMBER MAM ON RR.MEMBER_ID = MAM.MEMBER_ID 
ORDER BY
    REVIEW_DATE,
    REVIEW_TEXT;
