-- [programmersSQL] 부서별 평균 연봉 조회하기
SELECT
    d.DEPT_ID,
    d.DEPT_NAME_EN,
    ROUND(AVG(e.SAL), 0)AS AVG_SAL

FROM
    HR_EMPLOYEES e
    JOIN HR_DEPARTMENT d ON e.DEPT_ID = d.DEPT_ID
GROUP BY e.DEPT_ID
ORDER BY AVG_SAL DESC
;