-- [programmers]식품분류별 가장 비싼 식품의 정보 조회하기

SELECT FP.CATEGORY, FP.PRICE AS MAX_PRICE, FP.PRODUCT_NAME
FROM FOOD_PRODUCT AS FP
JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY = '과자' OR CATEGORY = '국' OR CATEGORY='김치' OR CATEGORY='식용유'
    GROUP BY CATEGORY
) AS MF
ON FP.CATEGORY = MF.CATEGORY AND FP.PRICE = MF.MAX_PRICE
ORDER BY MAX_PRICE DESC;
