-- [programmersSQL]상품 별 오프라인 매출 구하기
WITH PRODUCT_OFFLINE_SALE AS(
    SELECT 
        P.PRODUCT_CODE,
        SUM(OS.SALES_AMOUNT) * P.PRICE AS SALES
    FROM
        PRODUCT P
        JOIN OFFLINE_SALE OS ON P.PRODUCT_ID = OS.PRODUCT_ID
    GROUP BY P.PRODUCT_ID, P.PRODUCT_CODE, P.PRICE
)

SELECT 
    POS.PRODUCT_CODE, POS.SALES
FROM
    PRODUCT_OFFLINE_SALE POS
ORDER BY POS.SALES DESC, POS.PRODUCT_CODE ASC;
;

