-- [programmers]대여 기록이 존재하는 자동차 리스트 구하기

SELECT DISTINCT RCA.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS RCA
JOIN (
    SELECT RCRH.CAR_ID AS CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS RCRH
    WHERE MONTH(RCRH.START_DATE) = 10
) AS SRCA ON RCA.CAR_ID = SRCA.CAR_ID
WHERE RCA.CAR_TYPE = '세단'
ORDER BY RCA.CAR_ID DESC;
