-- [programmersSQL] 특정 조건을 만족하는 물고기별 수와 최대 길이 구하기
SELECT
    COUNT(*) AS FISH_COUNT,
    MAX(COALESCE(FI.LENGTH, 10)) AS MAX_LENGTH,
    FI.FISH_TYPE
FROM
    FISH_INFO FI
GROUP BY FI.FISH_TYPE
HAVING AVG(COALESCE(FI.LENGTH, 10)) >= 33
ORDER BY FI.FISH_TYPE
;

