-- [programmersSQL] 업그레이드 할 수 없는 아이템 구하기
SELECT 
    II.ITEM_ID, 
    II.ITEM_NAME, 
    II.RARITY
FROM ITEM_INFO II
LEFT JOIN ITEM_TREE IT ON II.ITEM_ID = IT.PARENT_ITEM_ID
WHERE IT.PARENT_ITEM_ID IS NULL
ORDER BY II.ITEM_ID DESC;



